version: '3.4'

configs:
  pub_key:
    file: ./.configs/pub_key
secrets:
  ssh_user:
    file: ./.secrets/ssh_user
  ssh_key:
    file: ./.secrets/ssh_key
volumes:
  app_src:
    external: true

services:
  vscode:
    image: 
      docker-vscode
    build: .
    ports:
      - "8022:22"
    volumes:
      - type: volume
        source: app_src
        target: /usr/src/my_app
    configs:
      - pub_key
    secrets:
      - ssh_user
      - ssh_key
