version: '3.4'

configs:
  pubkey:
    file: ./.configs/pubkey
secrets:
  ssh_user:
    file: ./.secrets/ssh_user
  ssh_key:
    file: ./.secrets/ssh_key

services:
  vscode:
    image: 
      docker-vscode
    build: .
    ports:
      - "8022:22"

volumes:
  - ..:/repos